name: CI
run-name: ${{ github.actor }} / ${{ github.workflow }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew build -x test --warning-mode none
